---
- hosts: all
  become: yes
  tasks:
  - name: install webserve(apache2) on ubuntu20 node
    apt:
      name: apache2
      state: present

  - name: start the apache2 services
    service:  
      name: apache2
      state: started
